namespace BetterGIProWpf.Services.Community;
public class ScriptVersion { public required string Commit { get; set; } public required string Parent { get; set; } public required string Message { get; set; } public DateTime Time { get; set; } = DateTime.Now; public required string ScriptJson { get; set; } public List<string> Branches { get; set; } = new(); }
public class CommunityScript { public required string Id { get; set; } public required string Name { get; set; } public string VideoSourceUrl { get; set; } = ""; public DateTime ParsedAt { get; set; } = DateTime.Now; public string ModelVersion { get; set; } = "1.0"; public string GameVersion { get; set; } = ""; public double SuccessRate { get; set; } = 0.5; public int ReviewCount { get; set; } public double Rating { get; set; } public string HeadCommit { get; set; } = ""; }
public class ScriptVersionManager {
    private readonly Dictionary<string, List<ScriptVersion>> _hist = new(); private readonly Dictionary<string, CommunityScript> _meta = new(); private readonly Dictionary<string, HashSet<string>> _reviewers = new(); private readonly object _lock = new();
    public int ScriptCount { get { lock (_lock) return _meta.Count; } }
    public string Init(string id, string name, string json, string videoUrl="", string gv="", string mv="1.0") { var c = Hash(id+json+Guid.NewGuid()); lock (_lock) { _hist[id] = new() { new() { Commit=c, Parent="", Message="init", ScriptJson=json } }; _meta[id] = new CommunityScript { Id=id, Name=name, VideoSourceUrl=videoUrl, GameVersion=gv, ModelVersion=mv, HeadCommit=c }; } return c; }
    public string Commit(string id, string json, string msg) { var c = Hash(id+json+Guid.NewGuid()); lock (_lock) { if (!_hist.TryGetValue(id, out var l) || l.Count==0) return Init(id, id, json); var p = _meta[id].HeadCommit; l.Add(new ScriptVersion { Commit=c, Parent=p, Message=msg, ScriptJson=json }); _meta[id].HeadCommit = c; } return c; }
    public string? Rollback(string id, string c) { lock (_lock) { if (!_hist.TryGetValue(id, out var l)) return null; var v = l.FirstOrDefault(x => x.Commit==c); if (v==null) return null; _meta[id].HeadCommit = c; return v.ScriptJson; } }
    public double Rate(string id, string reviewer, int stars, double successRate) { stars = Math.Clamp(stars,1,5); lock (_lock) { if (!_meta.TryGetValue(id, out var s)) return 0; if (!_reviewers.TryGetValue(id, out var set)) { set = new(); _reviewers[id] = set; } if (!set.Add(reviewer)) return s.Rating; s.ReviewCount++; var w = 0.5 + successRate; s.Rating = (s.Rating*(s.ReviewCount-1) + stars*w)/s.ReviewCount; return s.Rating; } }
    private static string Hash(string s) { using var sha = System.Security.Cryptography.SHA256.Create(); return Convert.ToHexString(sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(s)))[..12].ToLowerInvariant(); }
}
