using System.Globalization; using System.Text.Json; namespace BetterGIProWpf.Services.GuideBrowser;
public static class GuideFrameCapture {
    public static List<double> ComputeSampleTimes(double dur, int max=12) { var t = new List<double>(); if (dur<=0) { for (int i=0;i<6;i++) t.Add(0); return t; } int c = Math.Clamp((int)Math.Ceiling(dur/4.0),3,max); for (int i=0;i<c;i++) { double x = i==c-1 ? dur*0.97 : dur*i/c; t.Add(Math.Round(x,3)); } return t; }
    public static string BuildSeekScript(double t) => $"(async()=>{{const v=document.querySelector('video');if(!v)return 'no-video';v.muted=true;try{{v.play();}}catch(e){{}}v.currentTime={t.ToString("0.000",CultureInfo.InvariantCulture)};await new Promise(r=>{{const c=()=>{{if(v.readyState>=2&&Math.abs(v.currentTime-{t.ToString("0.000",CultureInfo.InvariantCulture)})<0.05)r('ok');else setTimeout(c,120);}};setTimeout(()=>r('timeout'),6000);c();}});return 'ok';}})()";
    public static string BuildCanvasScript(double t) => $"(async()=>{{const v=document.querySelector('video');if(!v)return JSON.stringify({{ok:false}});v.muted=true;try{{v.play();}}catch(e){{}}v.currentTime={t.ToString("0.000",CultureInfo.InvariantCulture)};await new Promise(r=>{{const c=()=>{{if(v.readyState>=2)r(1);else setTimeout(c,120);}};setTimeout(()=>r(0),6000);c();}});await new Promise(r=>setTimeout(r,250));const w=640,h=Math.max(120,Math.round(640*v.videoHeight/v.videoWidth));const cv=document.createElement('canvas');cv.width=w;cv.height=h;const x=cv.getContext('2d');try{{x.drawImage(v,0,0,w,h);return JSON.stringify({{ok:true,data:cv.toDataURL('image/jpeg',0.78),w,h}});}}catch(e){{return JSON.stringify({{ok:false,err:'cors'}});}}}})()";
    public static bool TrySaveCanvasFrame(string json, string path) { try { using var d = JsonDocument.Parse(json); var r = d.RootElement; if (r.TryGetProperty("ok", out var ok) && ok.GetBoolean()) { var data = r.GetProperty("data").GetString() ?? ""; var i = data.IndexOf("base64,", StringComparison.OrdinalIgnoreCase); if (i<0) return false; var b = Convert.FromBase64String(data[(i+7)..]); File.WriteAllBytes(path, b); return true; } } catch { } return false; }
    public static byte[] ThumbGray(byte[] img) { try { using var ms = new MemoryStream(img); using var bmp = new System.Drawing.Bitmap(ms); const int tw=32, th=18; var o = new byte[tw*th]; for (int y=0;y<th;y++) { int sy = Math.Min(bmp.Height-1,(int)((y+0.5)/th*bmp.Height)); for (int x=0;x<tw;x++) { int sx = Math.Min(bmp.Width-1,(int)((x+0.5)/tw*bmp.Width)); var c = bmp.GetPixel(sx,sy); o[y*tw+x] = (byte)((c.R*299+c.G*587+c.B*114)/1000); } } return o; } catch { return Array.Empty<byte>(); } }
    public static float ThumbDiff(byte[] a, byte[] b) { if (a.Length!=b.Length||a.Length==0) return 1f; double s=0; for (int i=0;i<a.Length;i+=2) s+=Math.Abs(a[i]-b[i]); return (float)(s/(a.Length/2)/255.0); }
    public static bool IsDup(byte[] a, byte[] b, float th=0.08f) => a.Length>0&&b.Length>0&&ThumbDiff(a,b)<th;
}
