using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BetterGIProWpf.Services.NitroGen;
using BetterGIProWpf.Services.Vision;

namespace BetterGIProWpf.Services.Recognition;

/// <summary>
/// 持续视频识别器（2 FPS = 每 500ms 一帧，每秒识别两次）。
/// </summary>
public sealed class ContinuousRecognizer : IDisposable
{
    public sealed record Step(double TimeSec, string OcrText, string Action, string Target, double DurationSec);
    public Func<Task<byte[]?>>? FrameProvider { get; set; }
    public Func<Task<double>>? CurrentTimeProvider { get; set; }
    public Func<string, (string Action, string Target)>? OcrToAction { get; set; }
    public Func<string, string, Task<string>>? UploadToGitHub { get; set; }
    public event Action<int, string, int>? OnTick;
    public event Action<string, string>? OnCompleted;

    private CancellationTokenSource? _cts;
    private Timer? _timer;
    private readonly object _lock = new();
    private readonly List<Step> _steps = new();
    private int _frameCount;
    private string? _currentScriptPath;
    private string? _currentJsDir;
    private DateTime _startAt;

    public TimeSpan Interval { get; set; } = TimeSpan.FromMilliseconds(500);
    public string UserRoot { get; set; } = Path.Combine(AppContext.BaseDirectory, "User");
    public bool IsRunning { get; private set; }
    public int FrameCount { get { lock (_lock) return _frameCount; } }
    public int StepCount { get { lock (_lock) return _steps.Count; } }
    public IReadOnlyList<Step> GetSteps() { lock (_lock) return _steps.ToList(); }

    public static (string Action, string Target) DefaultOcrToAction(string text)
    {
        if (string.IsNullOrWhiteSpace(text)) return ("wait", "");
        var t = text;
        if (t.Contains("传送") || t.Contains("锚点")) return ("teleport", t);
        if (t.Contains("采集") || t.Contains("矿") || t.Contains("水晶")) return ("collect", t);
        if (t.Contains("对话") || t.Contains("npc") || t.Contains("任务")) return ("dialogue", t);
        if (t.Contains("战斗") || t.Contains("攻击") || t.Contains("击杀") || t.Contains("boss", StringComparison.OrdinalIgnoreCase)) return ("combat", t);
        if (t.Contains("宝箱") || t.Contains("开启")) return ("chest", t);
        if (t.Contains("跑") || t.Contains("移动") || t.Contains("前进")) return ("walk", t);
        if (t.Contains("技能") || t.Contains("元素")) return ("skill", t);
        if (t.Contains("冲刺") || t.Contains("闪避")) return ("sprint", t);
        return ("unknown", t);
    }

    public void Start(string scriptName)
    {
        if (IsRunning) return;
        _cts = new CancellationTokenSource();
        _steps.Clear();
        _frameCount = 0;
        _startAt = DateTime.Now;
        var autoDir = Path.Combine(UserRoot, "AutoFight");
        var scriptDir = Path.Combine(UserRoot, "ScriptGroup", SafeName(scriptName));
        Directory.CreateDirectory(autoDir);
        Directory.CreateDirectory(scriptDir);
        var stamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
        _currentScriptPath = Path.Combine(autoDir, $"{SafeName(scriptName)}_{stamp}.txt");
        _currentJsDir = scriptDir;
        File.WriteAllText(_currentScriptPath,
            $"# BetterGI AutoFight 持续识别脚本（2 FPS · {DateTime.Now:yyyy-MM-dd HH:mm:ss}）\n" +
            $"# 间隔 500ms 自动抓帧 + OCR → 操作\n" +
            $"# 指令集: attack/skill/burst/charge/sprint/jump/walk/interact/wait;时长[;参数]\n",
            Encoding.UTF8);
        File.WriteAllText(Path.Combine(scriptDir, "manifest.json"), JsonSerializer.Serialize(new
        {
            manifest_version = 1, name = scriptName, version = "1.0.0", main = "main.js",
            description = "持续识别自动生成（2 FPS）",
            generated_at = DateTime.UtcNow.ToString("o"),
            source = "continuous-recognizer-2fps"
        }, new JsonSerializerOptions { WriteIndented = true }));
        File.WriteAllText(Path.Combine(scriptDir, "main.js"),
            "// auto-generated by ContinuousRecognizer\nmodule.exports = async function(ctx){try{\n  // steps appended at runtime\n}catch(e){console.log(e);}};\n");
        IsRunning = true;
        _timer = new Timer(_ => _ = TickAsync(), null, TimeSpan.Zero, Interval);
        OnTick?.Invoke(0, "持续识别已启动（2 FPS）", 0);
    }

    public async Task<string> StopAsync()
    {
        if (!IsRunning) return "未在运行";
        IsRunning = false;
        _timer?.Dispose();
        _cts?.Cancel();
        var jsPath = Path.Combine(_currentJsDir!, "main.js");
        var sb = new StringBuilder();
        sb.AppendLine("// auto-generated by ContinuousRecognizer (2 FPS)");
        sb.AppendLine($"// total steps: {_steps.Count}, frames: {_frameCount}");
        sb.AppendLine("module.exports = async function (ctx) {");
        sb.AppendLine("  try {");
        foreach (var s in _steps)
        {
            sb.AppendLine($"    // [{s.TimeSec:0.00}s] {s.Action}: {s.OcrText}");
            sb.AppendLine($"    await ctx.wait({Math.Max(200, (int)(s.DurationSec * 1000))});");
            sb.AppendLine("    if (ctx && ctx.isCancelled && ctx.isCancelled()) return;");
        }
        sb.AppendLine("  } catch (e) { console.log('err: ' + e); }");
        sb.AppendLine("};");
        await File.WriteAllTextAsync(jsPath, sb.ToString(), Encoding.UTF8);
        await File.AppendAllTextAsync(_currentScriptPath!,
            $"\n# end · steps={_steps.Count} · frames={_frameCount} · dur={(DateTime.Now - _startAt).TotalSeconds:0.0}s\n",
            Encoding.UTF8);
        string uploadResult = "未配置上传回调";
        if (UploadToGitHub != null && _currentScriptPath != null)
        {
            try
            {
                var content = await File.ReadAllTextAsync(_currentScriptPath, Encoding.UTF8);
                uploadResult = await UploadToGitHub(_currentScriptPath, content);
            }
            catch (Exception ex) { uploadResult = "上传失败: " + ex.Message; }
        }
        OnCompleted?.Invoke(_currentScriptPath!, uploadResult);
        return $"已停止 · {_frameCount} 帧 · {_steps.Count} 步 · 脚本: {_currentScriptPath}\n{uploadResult}";
    }

    private async Task TickAsync()
    {
        if (!IsRunning || _cts!.IsCancellationRequested) return;
        try
        {
            byte[]? jpeg = null;
            double videoTime = 0;
            if (FrameProvider != null) jpeg = await FrameProvider();
            if (CurrentTimeProvider != null) { try { videoTime = await CurrentTimeProvider(); } catch { } }
            if (jpeg == null || jpeg.Length == 0) return;
            string ocrText = "";
            try
            {
                using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(3) };
                var b64 = Convert.ToBase64String(jpeg);
                var resp = await http.PostAsync("http://127.0.0.1:5004/ocr",
                    new StringContent(JsonSerializer.Serialize(new { image = b64 }), Encoding.UTF8, "application/json"));
                if (resp.IsSuccessStatusCode)
                {
                    var json = await resp.Content.ReadAsStringAsync();
                    using var doc = JsonDocument.Parse(json);
                    if (doc.RootElement.TryGetProperty("text", out var tEl)) ocrText = tEl.GetString() ?? "";
                }
            }
            catch { }

            // P1-2/9：写入全局最新 OCR 文本，供教练/问答页实时读取
            if (!string.IsNullOrWhiteSpace(ocrText))
            {
                AppState.LastOcrText = ocrText;
                AppState.LastRecognitionAt = DateTime.Now;
            }

            var rule = OcrToAction ?? DefaultOcrToAction;
            var (action, target) = rule(ocrText);
            if (!string.IsNullOrWhiteSpace(ocrText) && action != "unknown")
            {
                var step = new Step(videoTime, ocrText, action, target, 0.5);
                lock (_lock) _steps.Add(step);
                var op = action switch
                {
                    "teleport" => "teleport", "collect" => "interact", "dialogue" => "interact",
                    "combat" => "attack", "chest" => "interact", "walk" => "walk",
                    "skill" => "skill", "sprint" => "sprint", _ => "wait",
                };
                await File.AppendAllTextAsync(_currentScriptPath!, $"{op};0.5;{target}\n", Encoding.UTF8);
            }
            lock (_lock)
            {
                _frameCount++;
                OnTick?.Invoke(_frameCount, ocrText, _steps.Count);
            }
        }
        catch (Exception ex) { Debug.WriteLine($"[ContinuousRecognizer] tick err: {ex.Message}"); }
    }

    private static string SafeName(string s)
    {
        var sb = new StringBuilder();
        foreach (var c in s) sb.Append(char.IsLetterOrDigit(c) || c is '_' or '-' ? c : '_');
        return sb.Length == 0 ? "script" : sb.ToString();
    }

    public void Dispose() { _timer?.Dispose(); _cts?.Dispose(); }
}
