            TelemetryLog.AppendText($"  B 分布: {string.Join(", ", g2)}\n");
            var diff = Math.Abs(a1.Count - a2.Count);
            TelemetryLog.AppendText($"  步数差: {diff}\n");
            double t1 = 0, t2 = 0;
            if (a1.Count > 0 && a1[^1].TryGetProperty("TimeSec", out var te1)) t1 = te1.GetDouble();
            if (a2.Count > 0 && a2[^1].TryGetProperty("TimeSec", out var te2)) t2 = te2.GetDouble();
            TelemetryLog.AppendText($"  总耗时: {t1:F1}s vs {t2:F1}s (差 {Math.Abs(t1-t2):F1}s)\n");
            var dev1 = a1.Count(x => x.TryGetProperty("Action", out var ac) && ac.GetString() == "wait");
            var dev2 = a2.Count(x => x.TryGetProperty("Action", out var ac) && ac.GetString() == "wait");
            TelemetryLog.AppendText($"  等待/偏离点: {dev1} vs {dev2}\n");